// DashboardModel
// Generated by Flutter Bunny Cli🐰

class DashboardModel {
  final String id;
  final String name;
  // Add more fields as needed
  
  DashboardModel({
    required this.id,
    required this.name,
  });
  
  factory DashboardModel.fromJson(Map<String, dynamic> json) {
    return DashboardModel(
      id: json['id'],
      name: json['name'],
    );
  }
  
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
    };
  }
}
